### ISSUE TITLE
palette ordering

### ISSUE THREAD

**Issue by davharris** [timcdlucas/palettetown#1]
Looks like a fun project.  I was thinking that it could be useful to re-order the colors so that a user that just uses the first 2-5 colors will reliably get perceptually distinct colors.  For example, the first three Charizard colors are all orange-brown and the first Porygon color looks a lot like its third color.

Maybe choose colors sequentially based on the distance to previously-chosen colors?

**Comment by timcdlucas** [comment]
This is pretty much what the argument spread does, though you have chose the number of colours.

I'm not totally happy with how it comes out though.

I wanted to keep ordered as an iron because you quickly lose the Pokemon's distinctness when you reorder.

**Comment by timcdlucas** [comment]
*I wanted to keep default ordered as an option

I was thinking I could maybe have spread = TRUE give the full palette with 5 good colours first. And that could possibly be the default parameter option.

There's some difficulties with doing this automatically though. A lot of pokemon have an almost white or almost black colour. These crop up in the clustering very quickly even though they should be avoided.

**Comment by davharris** [comment]
Whoops, didn't see that option.  Sorry.  

If you're worried about black and white, you could probably include them in the clustering and then exclude them from the output (effectively making sure that black and white have their own clusters and that they're never chosen).

If you want to get really fancy, we could talk about [better distance functions](https://en.wikipedia.org/wiki/Color_difference) for the color space and [alternative clustering methods](https://cran.r-project.org/web/packages/protoclust/index.html) that might require fewer ad-hoc hacks.  Of course, it is easy to go overboard with this sort of thing.

**Comment by timcdlucas** [comment]
Haha yeah, hardest thing with this is knowing when to stop because, ultimately, it's a pokemon palette... not my thesis.

I've excluded black already. It's the near blacks that are a bit more difficult. Of course I could remove anything that is 'near' black and 'near' white. But that's a bit more of a faff. And also you have to be a bit careful in that for some pokemon, near white is actually a major part of their colouration. e.g. [delibird](http://pokepalettes.com/#delibird). Even though that's not particularly useful in a palette, I think it should still be there.

I definitely would like to talk about distance functions. I remember HSV being better than RGB, but I couldn't remember if there was some proper perceptual difference space. I do want to overemphasize hue to an extent I think.

And with clustering I had a little read and a little play. The spherical clusters from Ward seemed better than methods that give more laderized type trees. If you know what's better, definitely let me know. It might not get implemented quickly though!

**Comment by timcdlucas** [comment]
I remember now. HCL was the colour space I wanted. I'll change that at some point.
